### ISSUE TITLE
Generalize toploop code

### ISSUE THREAD

**Issue by zepalmer** [JHU-PL-Lab/big-bang#1]
Some amount of the toploops for TinyBang, LittleBang, and BigBang could be generalized to reduce duplication.   Seems like a good idea, but not a huge priority.

Things that might be parametric in this generalization:
- Application name
- Version number
- Routines for well-formedness, evaluation, typechecking, etc.

**Comment by leafac** [comment]
I thought this would be piece of cake. It turns out to involve many small decisions that I don't want to make by my own at this moment. I'm going to leave this for later.

**Comment by leafac** [comment]
Some comments I leave for myself in the future, when I come back to this task:
- Base the abstraction on Big Bang lexer, parser and toploop.
- [ ] Figure out what the `Tiny_bang_parser_support.get_ast_position_hash ()` thing is all about.
  
   It's present on Little Bang parser, but I didn't use in Big Bang parser
   because it was ignored by the Little Bang toploop and didn't immediately
   understand what it was supposed to mean.
  
   For more information:
  1. [This](https://github.com/JHU-PL-Lab/big-bang/blob/850edbd6ec00a8ea7c60fb1469fd471502681aba/src/little-bang-parser/little_bang_parser.ml#L19) is where the data is generated.
  2. [And this](https://github.com/JHU-PL-Lab/big-bang/blob/850edbd6ec00a8ea7c60fb1469fd471502681aba/src/little-bang-toploop/little_bang_toploop.ml#L43) is where the data gets ignored.
  
  Maybe I'm going to need to reintroduce this in the Big Bang parser.
- [ ] Remove the `_generated` part of lexers and parsers names.
