### ISSUE TITLE
Add ref cell auto-dereferencing

### ISSUE THREAD

**Issue by maz** [JHU-PL-Lab/big-bang#13]
```
ref x = 5;
let y = 1;
x + y;;
```

fails with type error. Presumably this is because either:

a) closure rules for `ref` aren't implemented in tiny bang or,
b) big bang ought to be "dereferencing" the ref cells declared with the `ref x` syntax. In order to do that, however, big bang would need to maintain a symbol table (or some sort of structure) of which keyword was used to declare which variable. I'm not so sure this is a good idea, though, since we're trying to push analysis down into tiny bang.

**Comment by maz** [comment]
@zepalmer should I use the state monad for this?

**Comment by maz** [comment]
@rpglover64 told me to threaten to switch to haskell :)

**Comment by zepalmer** [comment]
@rpglover64 can get stuffed, with affection.  :)

EDIT: I wrote the following thinking that I was commenting on an issue related to TinyBang.  Please disregard.

~~Our usual model for this in previous designs has been that references are extracted by pattern matching.  That is, the LittleBang~~

```
(fun (ref x) -> x) (ref 0)
```

~~would evaluate to `0`.  Of course, the above is just the nested form of what the operational semantics would do.  As an added restriction, the only thing allowed within a `ref` pattern is an immediate variable, which is bound by the pattern match (much like the strict integer pattern matching).  It is not permissible to match e.g. labels within refs since that's a thoroughly complex problem due to the stateful nature of the reference cells and the way binding is handled.  Since we wanted to be able to pattern match on `ref` cells anyway, we designed the `ref` pattern match and then noticed that it obviated the need for an explicit deref operation.~~

**Comment by leafac** [comment]
I believe we do need a symbol table in Big Bang -> Little Bang translator in order to do the automatic dereferencing.

**Comment by rpglover64** [comment]
Right. That was the discussion we had during your office hours.

IIRC, the summary of that discussion is "Yes, a symbol table is useful and sufficient if all we want to do is distinguish variables into `let`-bound and `ref`-bound, but we also want to distinguish fields; to do that, we need a more pervasive translation step, though one which eliminates the need for a symbol table.

If we didn't want to support `ref` values in Big Bang, it would actually be easy, since Tiny Bang can case analyze a value and the translator can have it extract it if it's not a `ref`; however, we _would_ like to be able to have `ref` values in the future, which requires an explicit label tag; we came up with two such schemes:
1. Immutable values are wrapped in a `Let` label; mutable ones are wrapped in a `Ref` label and placed in a `ref` cell under that;
2. Values are left as values with no wrapping, and a distinguished label `Ref` is used to wrap Big Bang reference values.

**Comment by zepalmer** [comment]
IIRC, we decided upon option 2 above for the time being; we were going to see how that went because it looks like it'll be less clumsy in the long run.

That said, we also need to handle variable uses differently.  The BigBang `x` does not translate to LittleBang `x`; it instead translates to something like `__variableUnwrap x` where the function is defined as

```
let __variableUnwrap = (fun ref v -> v) & (fun v -> v) in ...
```

(assuming we're taking option 2 above).  Once again, we're assuming that there can be some dead code elimination to get rid of these calls in the case that it's statically known whether the argument is a reference cell or not, which should be the majority of the time.  That is, of course, an optimization, so we're not dealing with it yet.
