### ISSUE TITLE
Add variable shadowing

### ISSUE THREAD

**Issue by maz** [JHU-PL-Lab/big-bang#15]
Little bang should allow the following:

```
let x = 5 in let x = 6 in x;;
```

for example, should return 6.

**Comment by leafac** [comment]
@maz Why do you think that's the case?

Just so you know, in Big Bang we're explicitly disallowing such behavior. It doesn't increase expressiveness in a significant way and most of the times it's a source of confusion. We reached that conclusion after the experience of explaining how shadowing works in OCaml in Principles of Programming Languages.

**Comment by zepalmer** [comment]
@leafac Unfortunately, this is also material you missed as we were unable to coordinate a meeting.

This issue is motivated by the desire to handle operator overloading via shadowing.  For instance, the BigBang code

```
let condition = x > 5
```

would desugar to the LittleBang

```
let condition = __greaterThan x 5 in ...
```

This would allow us to accomplish operator overloading via intentional LittleBang shadowing:

```
overload > myComparisonFunction
let condition = x > 5
```

could desugar to

```
let __greaterThan = myComparisonFunction & __greaterThan in
let condition = __greaterThan x 5 in ...
```

This, of course, requires shadowing in LittleBang.

I still support the idea that BigBang should discourage or disallow variable shadowing.  But I think BigBang should be doing so itself rather than relying upon the underlying layers to give that guarantee.

**Comment by leafac** [comment]
@zepalmer Makes sense...

**Comment by maz** [comment]
Rather than adding a symbol table to both big bang and little bang, do you think it would make sense to push the overload keyword down into little bang, so that you need to explicitly annotate when you want to overload a variable?

**Comment by zepalmer** [comment]
There's some confusion here in the terminology you're using.

The `overload` keyword above refers to (imaginary) BigBang syntax for _operator overloading_.  Overloading in this case refers to using the same name at different arguments to select a different function.

Variable _shadowing_ is the practice of allowing a variable to be declared when a declaration of the same name is already present, taking the name to refer to the most recent declaration.

It would be possible to make LittleBang require explicit acknowledgement of variable shadowing.  A more interesting point is that we could allow shadowing in BigBang with explicit acknowledgement.  I view the act of preventing shadowing as something we do to improve the programmer's experience, so it only really matters in a language that the programmer will use.  I'm not interested in this feature for LittleBang (yet, at least) because I don't see a significant benefit in our having it.  Perhaps future bugs in as-yet-unwritten encodings may convince me otherwise.
