### ISSUE TITLE
Remove the list of updates from builtin operators?

### ISSUE THREAD

**Issue by maz** [JHU-PL-Lab/big-bang#33]
@zepalmer @leafac 

At the moment, builtin operators in the interpreter can return a list of updates to the environment, as well as the value that the builtin evaluates to. At the moment, every builtin operator (including `ref`) returns the empty list for the list of environmental updates (`ref` just mutates the environment itself). So, since nothing is using this list of updates, is it safe to remove it?

**Comment by leafac** [comment]
I'm not terribly knowledgeable on this part of the system. From what I understand either:
1. You can go ahead and remove it.
2. `ref` needs to be fixed and, instead of mutating the environment itself, it should return the environmental update instead. Somewhere else in the code this change should be performed.

I'd love to hear @zepalmer 's opinion.

**Comment by zepalmer** [comment]
Either of these solutions would work.  In the interpreter, the built-in case is handled like so:

``` ocaml
    | Builtin_redex(_, op, list_x) ->
      let (updates,v) = builtin_op env op list_x in
      List.iter (fun (x',v') -> update env x' v') updates;
      update env x v;
      evaluate env (Some x) t
```

The fact that `builtin_op` is doing updates as well is, of course, redundant.  But the rationale behind this is that is that, in the theory, there exist two functions for each built-in: an expression-level function and a type-level function.  Both functions return a set of updates.  In the case of the expression-level evaluation, they are substitutions to be made into the environment; in the case of the type system, they are constraints to be added to the global constraint set.  I had originally written the built-in operations to produce a list of updates as this would make the relationship with the specification more apparent, but we don't want to hammer the code into a shape that doesn't make sense.  I can go with either of @leafac's solutions, with a slight preference for number two if both are equivalent.

It's kind of hard to tell at the moment, since the type system isn't handling `ref`s atm anyway.
