### ISSUE TITLE
(proposed) Array_new constraint closure causes infinite loop

### ISSUE THREAD

**Issue by maz** [JHU-PL-Lab/big-bang#34]
An excerpt of the (infinite) constraints generated:

```
array_new:
{array __0* <: arr[], int <: __0*}
array_length:
{}

array_new:
{array __1* <: arr[], int <: __1*}
array_length:
{int <: length2[]}

array_new:
{array __2* <: arr[], int <: __2*}
array_length:
{int <: length2[], int <: length2[]}
```

According to @rpglover64 
This is because `Array_new` needs to create a "fresh variable" (these quotes are scary GRR).
So, we should modify `Builtin_ident` to take `tvar list`.

Tagging: @leafac @zepalmer

**Comment by zepalmer** [comment]
Is this on a branch I don't know about?  I don't see anything about arrays in constraint closure in any of our branches.  I also don't see anything about arrays in the TinyBang parser.

**Comment by maz** [comment]
I haven't pushed anything up yet, since I'm still adding constraints

**Comment by zepalmer** [comment]
Fair enough.  It's difficult to comment on anything at the moment, though, as I can't see it.  :)  Can you make a push if only for the purposes of discussion?

In general, I don't expect that you'd need to create fresh variables in arrays and, off the cuff, I'm very much opposed to modifying Builtin_ident in the fashion you describe.  This could, though, be because I'm not clear on what's going on.  Perhaps a glance at the source will solve that for me.

Do we have a formal spec for arrays?  Or were we planning to spec it out once we have a rough draft implementation?  I don't recall.

**Comment by rpglover64** [comment]
We don't have a formal spec; we were planning to draft the implementation first.

The problem (as I understand it) is this: an array type needs to have a type variable referring to its element type. It can't just reuse the variable from its argument, since lower bounds may be added to the array (by set) that don't correspond to lower bounds of its initial value. Every (syntactically distinct) `Array_new` call needs to produce a different type variable because it's creating a distinct array; in fact, the array being created is in bijection with the arguments, so it makes sense that its type variable is directly derived from them.

(This is not unique to arrays; I'm pretty sure refs suffer the same issues, at least if they're to be added via the builtin framework.)

I think you're uncomfortable because it makes the finiteness argument a lot more subtle. I believe it's still finite by the following reasoning: type variables don't flow (only types do), so there are only two ways to get new (non type-variable) lower bounds, namely starting with them and polyinstantiation; as long as the number of new type variables is limited by the number of (non tyvar) lower bounds, we're still safe.

The problem with the proposed change is that it doesn't enforce the invariant that `Builtin_ident` is only generated from what amounts to a (potentially polyinstantiated, non tyvar) lower bound. This might be something that can be addressed by splitting the type of identifiers, but I'm not sure.

On a related note, there should be a comment on the `Builtin_ident` constructor explaining the purpose of the int, and specifically saying that it should not be drawn from a source of fresh integers.

**Comment by maz** [comment]
Here's the branch: https://github.com/maz/big-bang/tree/add-array
