### ISSUE TITLE
Var_pattern translation into tiny bang

### ISSUE THREAD

**Issue by maz** [JHU-PL-Lab/big-bang#37]
This little bang code:

```
let f = fun v -> v in
f 10;;
```

gets translated into:

```
f = __2  { v = (); __2 = __3 * v; __3 = () } -> __1 = v; __5 = f; __4 = 10; __0 = __5 __4
```

Why are we using conjunction patterns here, instead of directly binding the variables? The reason why I'm asking is that, in tiny bang, for `Ref_filter` (and presumably for `Int_filter` too), we only want the inner `pvar` to either be an `Empty_filter` or just be bound to some variable. So, using the recursive `a_translate_pattern` function, this little bang code:

```
let f = fun ref v -> v in
f 10;;
```

gets translated into this tiny bang code:

```
f = __2  { v = (); __2 = ref __3; __3 = __4 * v; __4 = () } -> __1 = v; __6 = f; __5 = 10; __0 = __6 __5
```

instead of something like:

```
f = p0 \ { p0 = ref p1 } -> { r = p1 };
x = 10;
z = f x;
```

The generated tiny bang code gives an error:

```
Provided expression is ill-formed:
   Variable v is free in this expression
```

since the the well-formedness checker assumes that there won't be conjunction patterns in ref filters. So, should I change the ref filter pattern translation to explicitly generate non-conjunction filters, or should I change the generic `a_translate_pattern` on `Var_pattern` to not generate conjunction filters?

@zepalmer @leafac @rpglover64 @phsmenon

**Comment by maz** [comment]
Any thoughts? @zepalmer @leafac @rpglover64 @phsmenon

**Comment by leafac** [comment]
I'm sorry, but I don't have enough knowledge to comment on this. :cry: I remember implementing it, but I was pairing with @zepalmer and he might be in a better position to answer this. I know we implemented based on the thesis, if that helps.

**Comment by zepalmer** [comment]
The seemingly excessive use of conjunction patterns is a result of our desire to simplify the OCaml code that does the desugaring.  For every part of every pattern, we're picking a fresh variable so that we have a name to bind to the recursive desugaring result.  In a happy world, we wouldn't do this just for variables, but I felt no need to introduce a special case.  If you'd like to optimize that, feel free; it would definitely make the generated code a bit cleaner.

In this case, though, I think we should _also_ handle `ref` patterns specially in LittleBang, addressing the variable directly and viewing the ref pattern as a base case rather than recursing on the body of the `ref`.  That said, I'm having trouble finding the commit or branch where that stuff is right now.  Can you point me in the right direction?

**Comment by maz** [comment]
@zepalmer The code is in #14

**Comment by zepalmer** [comment]
Ah!  If I understand correctly, #14 reflects a set of changes that are meant to work around exactly the problem you are describing, yes?  If so, I can appreciate why you've written it the way you have.

If you'd like to tackle the problem of unnecessary conjunction patterns, you're welcome to do so.  In fact, doing that might simplify the handling of variable-only patterns like the contents of refs or primitive bindings.  It'd also have the advantage of making the generated code more readable.  It has the disadvantage of requiring work.

In a somewhat more concise answer to what I perceive your original question to be: there is no special reason that we were using conjunctions there; it was just convenient at the time.
